
services:
  backend-scraper-2.0:
    container_name: backend-scraper-2.0
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - ../backend-node-modules-scraper-2.0:/usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    # command: ./docker/dev.command.sh
    entrypoint: ['sh', './docker/dev.command.sh']
    env_file:
      - .env
    networks:
      - webnet-scraper-2.0
    depends_on:
      - postgres-scraper-2.0
      - rabbitmq-scraper-2.0

  postgres-scraper-2.0:
    container_name: postgres-scraper-2.0
    image: postgres:12.2
    networks:
      - webnet-scraper-2.0
    environment:
      TZ: GMT
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ../pgdata-scraper-2.0:/var/lib/postgresql/data

  rabbitmq-scraper-2.0:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq-scraper-2.0
    volumes:
      - ../rabbitmqdata_lib-scraper-2.0/:/var/lib/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - 15672:15672
    networks:
      - webnet-scraper-2.0

networks:
  webnet-scraper-2.0:
    name: webway-scraper-2.0
    driver: bridge
volumes:
  pgdata-scraper-2.0:
  rabbitmqdata-scraper-2.0:
  backend-node-modules-scraper-2.0:
  rabbitmqdata_lib-scraper-2.0:
