export const ProtocolIndicator = {
    ID: 0,
    SECP256K1: 1,
    ACTOR: 2,
    BLS: 3,
};

export const OpTypes = {
    NO_OP: 0,
    ADD_VERIFIER: 1,
    ADD_VERIFIED_CLIENT: 2,
    ADD_VERIFIED_DEAL: 3,
    DEAL_DID_NOT_ACTIVATE_CLIENT_RESTORED: 4,
    DEAL_DID_NOT_ACTIVATE_ALLOWANCE_RETURNED: 5,
    REMOVED_VERIFIER: 6,
    VERIFIER_ALLOWANCE_INCREASED: 7,
    UNTRACKED_DEAL_OP: 8,
    UNKNOWN: 100,
    ERROR_NO_MARKET_ACTOR: 101,
    ERROR_NO_ADDRESS_FOUND_FOR_DEAL: 102,
    ERROR_NO_VERIFIER_ALLOWANCE_CHANGE: 103,
    ERROR_NO_NEW_VERIFIED_CLIENTS: 104,
    ERROR_MORE_THAN_1_VERIFIED_CLIENTS_ADDED: 105,
    ERROR_ALLOWANCES_DO_NOT_MATCH: 106,
    ERROR_MORE_THAT_1_VERIFIED_CLIENT_REMOVED: 107,
};

export const getAllowanceMsgType = {
    VERIFIER: 0,
    VERIFIED_CLIENT: 1,
}
export class DeserializedListObject {
    items: {}
    objectCIDs: any[]
}